# Numpy: Numeric computing library

# Hands On!

In [2]:
import sys
import numpy as np

### Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Array Types

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_15248/217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [22]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c.dtype

dtype('<U1')

In [25]:
d = np.array([{'a':1}, sys])

In [26]:
d.dtype

dtype('O')

### Dimensions and Shapes

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape

(2, 3)

In [29]:
A.ndim

2

In [30]:
A.size

6

In [31]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8 ,7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [32]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [33]:
B.shape

(2, 2, 3)

In [34]:
B.ndim

3

In [35]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [37]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_15248/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [38]:
C

array([list([[12, 11, 10], [9, 8, 7]]), list([[6, 5, 4]])], dtype=object)

In [39]:
C.shape

(2,)

In [40]:
C.ndim

1

In [41]:
C.size

2

In [42]:
type(C[0])

list

### Indexing and Slicing of Matrices

In [43]:
# square matrix
A = np.array([
#.  0. 1. 2.    
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2 
])

In [44]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
A[1] #mengambil row ke 1

array([4, 5, 6])

In [46]:
A[1][0]

4

In [47]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [49]:
A[:2, 2:]

array([[3],
       [6]])

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
A[1] = np.array([10, 10, 10]) # custom mengubah nilai array

In [52]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [53]:
A[2] = 99 #mengubah nilai array

In [54]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary statistics

In [55]:
a = np.array([1, 2, 3, 4])

In [56]:
a.sum()

10

In [57]:
a.mean()

2.5

In [58]:
a.std()

1.118033988749895

In [59]:
a.var()

1.25

In [63]:
A = np.array([
    [1, 2, 3],
    [4, 10, 6],
    [7, 8, 9]
])

In [64]:
A.sum()

50

In [65]:
A.mean() # Nilai rata-rata

5.555555555555555

In [66]:
A.std()

3.02254900194121

In [67]:
A.var()

9.135802469135804

In [68]:
A.sum(axis=0)

array([12, 20, 18])

In [73]:
A.mean(axis=0)

array([4.        , 6.66666667, 6.        ])

In [74]:
A.mean(axis=1)

array([2.        , 6.66666667, 8.        ])

In [76]:
A.std(axis=0)

array([2.44948974, 3.39934634, 2.44948974])

In [78]:
A.std(axis=1)

array([0.81649658, 2.49443826, 0.81649658])

### Broadcasting and Vectorized operations

In [79]:
a = np.arange(4)

In [80]:
a

array([0, 1, 2, 3])

In [81]:
a + 10

array([10, 11, 12, 13])

In [82]:
a * 10

array([ 0, 10, 20, 30])

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a += 10

In [86]:
a

array([10, 11, 12, 13])

In [87]:
l = [0, 1, 2, 3]

In [88]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [90]:
a = np.arange(4)

In [91]:
a

array([0, 1, 2, 3])

In [92]:
b = np.array([10, 10, 10, 10])

In [93]:
b

array([10, 10, 10, 10])

In [94]:
a + b

array([10, 11, 12, 13])

In [95]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays

In [96]:
a = np.arange(4)

In [97]:
a

array([0, 1, 2, 3])

In [98]:
a[0], a[-1]

(0, 3)

In [99]:
a[[0,-1]]

array([0, 3])

In [100]:
a[[True, False, False, True]]

array([0, 3])

In [101]:
a

array([0, 1, 2, 3])

In [102]:
a >= 2

array([False, False,  True,  True])

In [103]:
a[a >= 2]

array([2, 3])

In [104]:
a.mean()

1.5

In [105]:
a[a > a.mean()]

array([2, 3])

In [106]:
a[~(a > a.mean())]

array([0, 1])

In [107]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [108]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [110]:
A = np.random.randint(100, size=(3,3))

In [111]:
A

array([[13, 44, 38],
       [86, 51, 54],
       [ 6, 25,  7]])

In [112]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([13, 38, 51,  6,  7])

In [113]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [114]:
A[A > 30]

array([44, 38, 86, 51, 54])

### Linear Algebra

In [115]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [116]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [117]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [118]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [119]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [120]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of objects in Memory

##### Int, floats

In [5]:
# An integet in python is > 24 bytes
sys.getsizeof(1)

28

In [6]:
# Long are even Larger
sys.getsizeof(10**100)

72

In [7]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [8]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [9]:
np.dtype(float).itemsize

8

##### List are even larger

In [10]:
# A one-element list
sys.getsizeof([1])

64

In [11]:
# An array of one element in numpy
np.array([1]).nbytes

4

##### And performance is also important

In [12]:
l = list(range(100000))

In [13]:
a = np.arange(100000)

In [14]:
%time np.sum(a ** 2)

Wall time: 6.31 ms


216474736

In [15]:
%time sum([x ** 2 for x in l])

Wall time: 56 ms


333328333350000

### Useful Numpy Function

##### Random

In [16]:
np.random.random(size=2)

array([0.98605281, 0.01386422])

In [17]:
np.random.normal(size=2)

array([-0.08595947, -0.37621236])

In [18]:
np.random.rand(2, 4)

array([[0.57976333, 0.98738893, 0.56596447, 0.87482154],
       [0.32309491, 0.10812029, 0.93057763, 0.00619523]])

##### Arange

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##### Reshape

In [22]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##### Linspace

In [24]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

##### Zeros, Ones, Empty

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((3, 3), dtype=np.int)

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_6944/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

##### Identity and Eye

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(8, 4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [46]:
"Hello World"[6]

'W'