In [1]:
import numpy as np
print(np.__version__)

1.20.3


## Array Creation

#### Create a numpy array of size 10, filled with zeros.

In [2]:
np.array([0] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create a numpy array with values ranging from 10 to 49

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a numpy matrix of 2*2 integers, filled with ones.

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.ones((3,2), dtype=np.float)

C:\Users\LENOVO\AppData\Local\Temp/ipykernel_5776/1711190876.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((3,2), dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.